# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import calibrate_pb2 as calibrate__pb2


class CalibrateStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CalibrateOnePort = channel.unary_unary(
                '/pb.Calibrate/CalibrateOnePort',
                request_serializer=calibrate__pb2.CalibrateOnePortRequest.SerializeToString,
                response_deserializer=calibrate__pb2.CalibrateOnePortResponse.FromString,
                )
        self.CalibrateTwoPort = channel.unary_unary(
                '/pb.Calibrate/CalibrateTwoPort',
                request_serializer=calibrate__pb2.CalibrateTwoPortRequest.SerializeToString,
                response_deserializer=calibrate__pb2.CalibrateTwoPortResponse.FromString,
                )


class CalibrateServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CalibrateOnePort(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CalibrateTwoPort(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CalibrateServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CalibrateOnePort': grpc.unary_unary_rpc_method_handler(
                    servicer.CalibrateOnePort,
                    request_deserializer=calibrate__pb2.CalibrateOnePortRequest.FromString,
                    response_serializer=calibrate__pb2.CalibrateOnePortResponse.SerializeToString,
            ),
            'CalibrateTwoPort': grpc.unary_unary_rpc_method_handler(
                    servicer.CalibrateTwoPort,
                    request_deserializer=calibrate__pb2.CalibrateTwoPortRequest.FromString,
                    response_serializer=calibrate__pb2.CalibrateTwoPortResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pb.Calibrate', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Calibrate(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CalibrateOnePort(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.Calibrate/CalibrateOnePort',
            calibrate__pb2.CalibrateOnePortRequest.SerializeToString,
            calibrate__pb2.CalibrateOnePortResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CalibrateTwoPort(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.Calibrate/CalibrateTwoPort',
            calibrate__pb2.CalibrateTwoPortRequest.SerializeToString,
            calibrate__pb2.CalibrateTwoPortResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
