# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calibrate.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='calibrate.proto',
  package='pb',
  syntax='proto3',
  serialized_options=b'Z/github.com/practable/pocket-vna-two-port/pkg/pb',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0f\x63\x61librate.proto\x12\x02pb\"J\n\x18\x43\x61librateOnePortResponse\x12\x11\n\tfrequency\x18\x01 \x03(\x01\x12\x1b\n\x06result\x18\x02 \x03(\x0b\x32\x0b.pb.Complex\"J\n\x18\x43\x61librateTwoPortResponse\x12\x11\n\tfrequency\x18\x01 \x03(\x01\x12\x1b\n\x06result\x18\x02 \x01(\x0b\x32\x0b.pb.SParams\"\xb3\x01\n\x17\x43\x61librateOnePortRequest\x12\x11\n\tfrequency\x18\x01 \x03(\x01\x12\x1a\n\x05short\x18\x02 \x03(\x0b\x32\x0b.pb.Complex\x12\x19\n\x04open\x18\x03 \x03(\x0b\x32\x0b.pb.Complex\x12\x19\n\x04load\x18\x04 \x03(\x0b\x32\x0b.pb.Complex\x12\x19\n\x04thru\x18\x05 \x03(\x0b\x32\x0b.pb.Complex\x12\x18\n\x03\x64ut\x18\x06 \x03(\x0b\x32\x0b.pb.Complex\"\xb3\x01\n\x17\x43\x61librateTwoPortRequest\x12\x11\n\tfrequency\x18\x01 \x03(\x01\x12\x1a\n\x05short\x18\x02 \x01(\x0b\x32\x0b.pb.SParams\x12\x19\n\x04open\x18\x03 \x01(\x0b\x32\x0b.pb.SParams\x12\x19\n\x04load\x18\x04 \x01(\x0b\x32\x0b.pb.SParams\x12\x19\n\x04thru\x18\x05 \x01(\x0b\x32\x0b.pb.SParams\x12\x18\n\x03\x64ut\x18\x06 \x01(\x0b\x32\x0b.pb.SParams\"q\n\x07SParams\x12\x18\n\x03s11\x18\x01 \x03(\x0b\x32\x0b.pb.Complex\x12\x18\n\x03s12\x18\x02 \x03(\x0b\x32\x0b.pb.Complex\x12\x18\n\x03S21\x18\x03 \x03(\x0b\x32\x0b.pb.Complex\x12\x18\n\x03S22\x18\x04 \x03(\x0b\x32\x0b.pb.Complex\"%\n\x07\x43omplex\x12\x0c\n\x04imag\x18\x01 \x01(\x01\x12\x0c\n\x04real\x18\x02 \x01(\x01\x32\xad\x01\n\tCalibrate\x12O\n\x10\x43\x61librateOnePort\x12\x1b.pb.CalibrateOnePortRequest\x1a\x1c.pb.CalibrateOnePortResponse\"\x00\x12O\n\x10\x43\x61librateTwoPort\x12\x1b.pb.CalibrateTwoPortRequest\x1a\x1c.pb.CalibrateTwoPortResponse\"\x00\x42\x31Z/github.com/practable/pocket-vna-two-port/pkg/pbb\x06proto3'
)




_CALIBRATEONEPORTRESPONSE = _descriptor.Descriptor(
  name='CalibrateOnePortResponse',
  full_name='pb.CalibrateOnePortResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='frequency', full_name='pb.CalibrateOnePortResponse.frequency', index=0,
      number=1, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='result', full_name='pb.CalibrateOnePortResponse.result', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=97,
)


_CALIBRATETWOPORTRESPONSE = _descriptor.Descriptor(
  name='CalibrateTwoPortResponse',
  full_name='pb.CalibrateTwoPortResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='frequency', full_name='pb.CalibrateTwoPortResponse.frequency', index=0,
      number=1, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='result', full_name='pb.CalibrateTwoPortResponse.result', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=99,
  serialized_end=173,
)


_CALIBRATEONEPORTREQUEST = _descriptor.Descriptor(
  name='CalibrateOnePortRequest',
  full_name='pb.CalibrateOnePortRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='frequency', full_name='pb.CalibrateOnePortRequest.frequency', index=0,
      number=1, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='short', full_name='pb.CalibrateOnePortRequest.short', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='open', full_name='pb.CalibrateOnePortRequest.open', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='load', full_name='pb.CalibrateOnePortRequest.load', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='thru', full_name='pb.CalibrateOnePortRequest.thru', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dut', full_name='pb.CalibrateOnePortRequest.dut', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=176,
  serialized_end=355,
)


_CALIBRATETWOPORTREQUEST = _descriptor.Descriptor(
  name='CalibrateTwoPortRequest',
  full_name='pb.CalibrateTwoPortRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='frequency', full_name='pb.CalibrateTwoPortRequest.frequency', index=0,
      number=1, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='short', full_name='pb.CalibrateTwoPortRequest.short', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='open', full_name='pb.CalibrateTwoPortRequest.open', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='load', full_name='pb.CalibrateTwoPortRequest.load', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='thru', full_name='pb.CalibrateTwoPortRequest.thru', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dut', full_name='pb.CalibrateTwoPortRequest.dut', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=358,
  serialized_end=537,
)


_SPARAMS = _descriptor.Descriptor(
  name='SParams',
  full_name='pb.SParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='s11', full_name='pb.SParams.s11', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='s12', full_name='pb.SParams.s12', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='S21', full_name='pb.SParams.S21', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='S22', full_name='pb.SParams.S22', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=539,
  serialized_end=652,
)


_COMPLEX = _descriptor.Descriptor(
  name='Complex',
  full_name='pb.Complex',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='imag', full_name='pb.Complex.imag', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='real', full_name='pb.Complex.real', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=654,
  serialized_end=691,
)

_CALIBRATEONEPORTRESPONSE.fields_by_name['result'].message_type = _COMPLEX
_CALIBRATETWOPORTRESPONSE.fields_by_name['result'].message_type = _SPARAMS
_CALIBRATEONEPORTREQUEST.fields_by_name['short'].message_type = _COMPLEX
_CALIBRATEONEPORTREQUEST.fields_by_name['open'].message_type = _COMPLEX
_CALIBRATEONEPORTREQUEST.fields_by_name['load'].message_type = _COMPLEX
_CALIBRATEONEPORTREQUEST.fields_by_name['thru'].message_type = _COMPLEX
_CALIBRATEONEPORTREQUEST.fields_by_name['dut'].message_type = _COMPLEX
_CALIBRATETWOPORTREQUEST.fields_by_name['short'].message_type = _SPARAMS
_CALIBRATETWOPORTREQUEST.fields_by_name['open'].message_type = _SPARAMS
_CALIBRATETWOPORTREQUEST.fields_by_name['load'].message_type = _SPARAMS
_CALIBRATETWOPORTREQUEST.fields_by_name['thru'].message_type = _SPARAMS
_CALIBRATETWOPORTREQUEST.fields_by_name['dut'].message_type = _SPARAMS
_SPARAMS.fields_by_name['s11'].message_type = _COMPLEX
_SPARAMS.fields_by_name['s12'].message_type = _COMPLEX
_SPARAMS.fields_by_name['S21'].message_type = _COMPLEX
_SPARAMS.fields_by_name['S22'].message_type = _COMPLEX
DESCRIPTOR.message_types_by_name['CalibrateOnePortResponse'] = _CALIBRATEONEPORTRESPONSE
DESCRIPTOR.message_types_by_name['CalibrateTwoPortResponse'] = _CALIBRATETWOPORTRESPONSE
DESCRIPTOR.message_types_by_name['CalibrateOnePortRequest'] = _CALIBRATEONEPORTREQUEST
DESCRIPTOR.message_types_by_name['CalibrateTwoPortRequest'] = _CALIBRATETWOPORTREQUEST
DESCRIPTOR.message_types_by_name['SParams'] = _SPARAMS
DESCRIPTOR.message_types_by_name['Complex'] = _COMPLEX
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CalibrateOnePortResponse = _reflection.GeneratedProtocolMessageType('CalibrateOnePortResponse', (_message.Message,), {
  'DESCRIPTOR' : _CALIBRATEONEPORTRESPONSE,
  '__module__' : 'calibrate_pb2'
  # @@protoc_insertion_point(class_scope:pb.CalibrateOnePortResponse)
  })
_sym_db.RegisterMessage(CalibrateOnePortResponse)

CalibrateTwoPortResponse = _reflection.GeneratedProtocolMessageType('CalibrateTwoPortResponse', (_message.Message,), {
  'DESCRIPTOR' : _CALIBRATETWOPORTRESPONSE,
  '__module__' : 'calibrate_pb2'
  # @@protoc_insertion_point(class_scope:pb.CalibrateTwoPortResponse)
  })
_sym_db.RegisterMessage(CalibrateTwoPortResponse)

CalibrateOnePortRequest = _reflection.GeneratedProtocolMessageType('CalibrateOnePortRequest', (_message.Message,), {
  'DESCRIPTOR' : _CALIBRATEONEPORTREQUEST,
  '__module__' : 'calibrate_pb2'
  # @@protoc_insertion_point(class_scope:pb.CalibrateOnePortRequest)
  })
_sym_db.RegisterMessage(CalibrateOnePortRequest)

CalibrateTwoPortRequest = _reflection.GeneratedProtocolMessageType('CalibrateTwoPortRequest', (_message.Message,), {
  'DESCRIPTOR' : _CALIBRATETWOPORTREQUEST,
  '__module__' : 'calibrate_pb2'
  # @@protoc_insertion_point(class_scope:pb.CalibrateTwoPortRequest)
  })
_sym_db.RegisterMessage(CalibrateTwoPortRequest)

SParams = _reflection.GeneratedProtocolMessageType('SParams', (_message.Message,), {
  'DESCRIPTOR' : _SPARAMS,
  '__module__' : 'calibrate_pb2'
  # @@protoc_insertion_point(class_scope:pb.SParams)
  })
_sym_db.RegisterMessage(SParams)

Complex = _reflection.GeneratedProtocolMessageType('Complex', (_message.Message,), {
  'DESCRIPTOR' : _COMPLEX,
  '__module__' : 'calibrate_pb2'
  # @@protoc_insertion_point(class_scope:pb.Complex)
  })
_sym_db.RegisterMessage(Complex)


DESCRIPTOR._options = None

_CALIBRATE = _descriptor.ServiceDescriptor(
  name='Calibrate',
  full_name='pb.Calibrate',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=694,
  serialized_end=867,
  methods=[
  _descriptor.MethodDescriptor(
    name='CalibrateOnePort',
    full_name='pb.Calibrate.CalibrateOnePort',
    index=0,
    containing_service=None,
    input_type=_CALIBRATEONEPORTREQUEST,
    output_type=_CALIBRATEONEPORTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='CalibrateTwoPort',
    full_name='pb.Calibrate.CalibrateTwoPort',
    index=1,
    containing_service=None,
    input_type=_CALIBRATETWOPORTREQUEST,
    output_type=_CALIBRATETWOPORTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CALIBRATE)

DESCRIPTOR.services_by_name['Calibrate'] = _CALIBRATE

# @@protoc_insertion_point(module_scope)
