#!/bin/bash
export JUMP_HOST_LOCAL_PORT=22
export JUMP_HOST_ACCESS=$(cat /etc/practable/jump.access)
export JUMP_HOST_TOKEN=$(cat /etc/practable/jump.token)
export JUMP_HOST_DEVELOPMENT=true
/usr/local/bin/jump host