#!/bin/sh
dataAccess=$(cat /etc/practable/st-ed0-data.access)
dataToken=$(cat /etc/practable/st-ed0-data.token)

curl -X POST -H "Content-Type: application/json" -d '{"stream":"data","destination":"'"${dataAccess}"'","id":"0","token":"'"${dataToken}"'"}' http://localhost:8888/api/destinations
