#!/bin/bash
export VNA_ADDR=localhost:9001
export VNA_BAUD=57600
export VNA_LOG_FILE=/var/log/vna/vna.log
export VNA_LOG_FORMAT=json
export VNA_LOG_LEVEL=info
export VNA_PORT=/dev/ttyUSB0
export VNA_TIMEOUT_USB=30s
export VNA_TIMEOUT_REQUEST=3m
export VNA_TOPIC=ws://localhost:8888/ws/data
vna unlock
vna stream
